kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: slate-core
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    protocol: TCP
#host
    port: 9200
#pod
    targetPort: 9200
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
  namespace: slate-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms4G -Xmx4G"
      volumes:
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: elasticsearch
#add this to sysctl.conf
#vm.max_map_count = 262144
